const datoJugadoresBrasil = {
    jugadores: {
        titulares: [
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Curtis Serra-Gras',
            id: 'sQjxmikC6HpDqJ22jUvA1',
            habilidades: {
              ataque: 63,
              defensa: 65,
              resistencia: 62,
            },
            posicion: 'ARQUERO',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars0.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Felix Solsona',
            id: 'YYTZEhPI-NC_-3g3EizKf',
            habilidades: {
              ataque: 67,
              defensa: 62,
              resistencia: 58,
            },
            posicion: 'DEFENSOR',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars1.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Curtis de Gomila',
            id: 'RaZREhBRWHmLU_MKcfovV',
            habilidades: {
              ataque: 58,
              defensa: 69,
              resistencia: 51,
            },
            posicion: 'DEFENSOR',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars2.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Vasco Salvador Herrero',
            id: 'eiu5M3LTMQ6mMUavALBzl',
            habilidades: {
              ataque: 69,
              defensa: 70,
              resistencia: 66,
            },
            posicion: 'DEFENSOR',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars3.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Bartolomé del Ayllón',
            id: 'moqjZS8lXUAs-2kbLgznp',
            habilidades: {
              ataque: 64,
              defensa: 57,
              resistencia: 61,
            },
            posicion: 'DEFENSOR',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars4.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Adalberto Hale',
            id: 'ZOAHFfY5NCdmkWM2wr7jF',
            habilidades: {
              ataque: 56,
              defensa: 51,
              resistencia: 59,
            },
            posicion: 'MEDIOCAMPISTA',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars5.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Felix Perez Sabater',
            id: 'MTOyv69BVbPQ54TVIk6sv',
            habilidades: {
              ataque: 67,
              defensa: 62,
              resistencia: 56,
            },
            posicion: 'MEDIOCAMPISTA',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars6.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Vasco de Gomila',
            id: 'Ke6ljki5rbYW27WWNwbg0',
            habilidades: {
              ataque: 53,
              defensa: 67,
              resistencia: 55,
            },
            posicion: 'MEDIOCAMPISTA',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars7.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Adrián Carson',
            id: 'DP8t28f4MYIlTFlg8zeyN',
            habilidades: {
              ataque: 58,
              defensa: 51,
              resistencia: 67,
            },
            posicion: 'MEDIOCAMPISTA',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars8.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Vasco del Ayllón',
            id: '-12Tte_8XEyQBCtjiiaSj',
            habilidades: {
              ataque: 62,
              defensa: 64,
              resistencia: 60,
            },
            posicion: 'DELANTERO',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars9.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Bartolomé Salvador Herrero',
            id: 'iy9PrtHZLq6qkGJ7XLy2D',
            habilidades: {
              ataque: 64,
              defensa: 70,
              resistencia: 70,
            },
            posicion: 'DELANTERO',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars10.png',
          },
        ],
        suplentes: [
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Joel Brock',
            id: 'hW9reTaFiJk-PxlBgEfQ-',
            habilidades: {
              ataque: 51,
              defensa: 70,
              resistencia: 64,
            },
            posicion: 'ARQUERO',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars11.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Adrián Solsona',
            id: 'mq_HN0lvp4WJkbF4vv-9f',
            habilidades: {
              ataque: 70,
              defensa: 59,
              resistencia: 70,
            },
            posicion: 'DEFENSOR',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars12.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Adalberto Salvador Herrero',
            id: 'd6mVOf6qpMuVm7gCstqGH',
            habilidades: {
              ataque: 61,
              defensa: 70,
              resistencia: 56,
            },
            posicion: 'MEDIOCAMPISTA',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars13.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Segismundo Luis de Páez',
            id: 'opPyvzu8cJjDPr3Aa3X5J',
            habilidades: {
              ataque: 63,
              defensa: 62,
              resistencia: 56,
            },
            posicion: 'MEDIOCAMPISTA',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars14.png',
          },
          {
            puedeJugar: true,
            jugadorEnVenta: false,
            nombre: 'Bartolomé Tucker',
            id: 'zjaDRBwb7wx_e3nbWOgcN',
            habilidades: {
              ataque: 55,
              defensa: 69,
              resistencia: 64,
            },
            posicion: 'DELANTERO',
            club: 'Brasil Sports',
            imagenPerfil: 'avataaars15.png',
          },
        ],
        deshabilitados: [],
      }
}

export default datoJugadoresBrasil