const brasilSports = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Brasil Sports",
  id: "k625VuQKwlmC0ngQxhho0",
  nacionalidad: "Brasil",
  logo: "logo8.jpg",
  keyPublica: "GBGA4S3FCR4V4ABO3FW5MAVCNZ2O5RRAZIX3YUDDKSQAFN33X57FC6SB",
  keyPrivada: "SBYH6JPWAHUNPMCFZGZY2VDHKCQHJ2YSSNRHSK7YTWKIABJ2FEZBLB4H",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Curtis Serra-Gras",
        id: "sQjxmikC6HpDqJ22jUvA1",
        habilidades: {
          ataque: 63,
          defensa: 65,
          resistencia: 62,
        },
        posicion: "arquero",
        club: "Brasil Sports",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Felix Solsona",
        id: "YYTZEhPI-NC_-3g3EizKf",
        habilidades: {
          ataque: 67,
          defensa: 62,
          resistencia: 58,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Curtis de Gomila",
        id: "RaZREhBRWHmLU_MKcfovV",
        habilidades: {
          ataque: 58,
          defensa: 69,
          resistencia: 51,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco Salvador Herrero",
        id: "eiu5M3LTMQ6mMUavALBzl",
        habilidades: {
          ataque: 69,
          defensa: 70,
          resistencia: 66,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé del Ayllón",
        id: "moqjZS8lXUAs-2kbLgznp",
        habilidades: {
          ataque: 64,
          defensa: 57,
          resistencia: 61,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adalberto Hale",
        id: "ZOAHFfY5NCdmkWM2wr7jF",
        habilidades: {
          ataque: 56,
          defensa: 51,
          resistencia: 59,
        },
        posicion: "mediocampista",
        club: "Brasil Sports",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Felix Perez Sabater",
        id: "MTOyv69BVbPQ54TVIk6sv",
        habilidades: {
          ataque: 67,
          defensa: 62,
          resistencia: 56,
        },
        posicion: "mediocampista",
        club: "Brasil Sports",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco de Gomila",
        id: "Ke6ljki5rbYW27WWNwbg0",
        habilidades: {
          ataque: 53,
          defensa: 67,
          resistencia: 55,
        },
        posicion: "mediocampista",
        club: "Brasil Sports",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Carson",
        id: "DP8t28f4MYIlTFlg8zeyN",
        habilidades: {
          ataque: 58,
          defensa: 51,
          resistencia: 67,
        },
        posicion: "mediocampista",
        club: "Brasil Sports",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco del Ayllón",
        id: "-12Tte_8XEyQBCtjiiaSj",
        habilidades: {
          ataque: 62,
          defensa: 64,
          resistencia: 60,
        },
        posicion: "delantero",
        club: "Brasil Sports",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Salvador Herrero",
        id: "iy9PrtHZLq6qkGJ7XLy2D",
        habilidades: {
          ataque: 64,
          defensa: 70,
          resistencia: 70,
        },
        posicion: "delantero",
        club: "Brasil Sports",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Brock",
        id: "hW9reTaFiJk-PxlBgEfQ-",
        habilidades: {
          ataque: 51,
          defensa: 70,
          resistencia: 64,
        },
        posicion: "arquero",
        club: "Brasil Sports",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Solsona",
        id: "mq_HN0lvp4WJkbF4vv-9f",
        habilidades: {
          ataque: 70,
          defensa: 59,
          resistencia: 70,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adalberto Salvador Herrero",
        id: "d6mVOf6qpMuVm7gCstqGH",
        habilidades: {
          ataque: 61,
          defensa: 70,
          resistencia: 56,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo Luis de Páez",
        id: "opPyvzu8cJjDPr3Aa3X5J",
        habilidades: {
          ataque: 63,
          defensa: 62,
          resistencia: 56,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Tucker",
        id: "zjaDRBwb7wx_e3nbWOgcN",
        habilidades: {
          ataque: 55,
          defensa: 69,
          resistencia: 64,
        },
        posicion: "defensa",
        club: "Brasil Sports",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};

const colombiaBulls = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Colombia Bulls",
  id: "P9pNIqllPJOibQBfQUunf",
  nacionalidad: "Colombia",
  logo: "logo7.jpg",
  keyPublica: "GBESV24U42TRV4KBW7VIVEXPJ4HBRRWSXXIC6GNZQ5HBG4R474BJCEUZ",
  keyPrivada: "SDUV5RGSI6JBI45364BDJ5HRH72JJGOHDHBMSFR3235U6HGRL4WNOEYT",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Hale",
        id: "yEuL_CgMSVh47fu1vyWSa",
        habilidades: {
          ataque: 62,
          defensa: 69,
          resistencia: 59,
        },
        posicion: "arquero",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ricardo Fitzgerald",
        id: "MhoUHIer9f6zgMVVP75XV",
        habilidades: {
          ataque: 55,
          defensa: 59,
          resistencia: 69,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Nicanor Perez Sabater",
        id: "t5HFWetBdxI9uunP9mH6k",
        habilidades: {
          ataque: 69,
          defensa: 53,
          resistencia: 58,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Nicanor Bryant",
        id: "FQqEVjjKvC4NNiK_P586-",
        habilidades: {
          ataque: 59,
          defensa: 66,
          resistencia: 64,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Eleuterio de Gomila",
        id: "izVNClCYsBW7VcPsdE1wM",
        habilidades: {
          ataque: 52,
          defensa: 59,
          resistencia: 62,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Fitzgerald",
        id: "AYH84rAB-7p4yF0qrMzPX",
        habilidades: {
          ataque: 57,
          defensa: 69,
          resistencia: 56,
        },
        posicion: "mediocampista",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Curtis Tucker",
        id: "wO15-I1kBXY-vOkFW-u8R",
        habilidades: {
          ataque: 55,
          defensa: 60,
          resistencia: 65,
        },
        posicion: "mediocampista",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé del Ayllón",
        id: "Kz1JEEFAsDFWrRDjVz3EZ",
        habilidades: {
          ataque: 67,
          defensa: 56,
          resistencia: 64,
        },
        posicion: "mediocampista",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Eleuterio Brock",
        id: "6DE0Rg9Oe5jXIQJVUkm_m",
        habilidades: {
          ataque: 68,
          defensa: 55,
          resistencia: 63,
        },
        posicion: "mediocampista",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Albano Huerta",
        id: "8vy3i7PK6p61Htp8BokT4",
        habilidades: {
          ataque: 64,
          defensa: 54,
          resistencia: 69,
        },
        posicion: "delantero",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Gil Huerta",
        id: "v3fK_x-Txlshn_TpZ1aOu",
        habilidades: {
          ataque: 56,
          defensa: 64,
          resistencia: 51,
        },
        posicion: "delantero",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Salvador Herrero",
        id: "MgrdaNz2Yt4UXw_935Chr",
        habilidades: {
          ataque: 68,
          defensa: 61,
          resistencia: 68,
        },
        posicion: "arquero",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Brock",
        id: "mSUR5-1jWi8nDPzzkgN7E",
        habilidades: {
          ataque: 51,
          defensa: 61,
          resistencia: 55,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Rosendo Hale",
        id: "Mb-pLmL_eqqGKrrst13Lt",
        habilidades: {
          ataque: 52,
          defensa: 64,
          resistencia: 57,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Brock",
        id: "gqivhMCpXbfUiwYN-NizL",
        habilidades: {
          ataque: 63,
          defensa: 60,
          resistencia: 56,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Brock",
        id: "wedwGfSA4Erajz5EYjfoP",
        habilidades: {
          ataque: 59,
          defensa: 58,
          resistencia: 65,
        },
        posicion: "defensa",
        club: "Colombia Bulls",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};

const paraguayFC = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Paraguay FC",
  id: "4XtfqzwoXprj_otsCBHaz",
  nacionalidad: "Paraguay",
  logo: "logo6.jpg",
  keyPublica: "GBTK42EAXIDZTTD2WIXKJWXHSDPQ5ICC4WMSP3MEICGPCCFPYFW25DG7",
  keyPrivada: "SBI2B2BJKRVOATRRWNWWSF6MQGPCTVF4DNKJ5P5CMLDD24CQPENOD3L7",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco Hale",
        id: "8txjw4cM11A2wwn-DNSqU",
        habilidades: {
          ataque: 69,
          defensa: 67,
          resistencia: 59,
        },
        posicion: "arquero",
        club: "Paraguay FC",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian del Ayllón",
        id: "ePMTpRcDF0dYX5YwVoVCV",
        habilidades: {
          ataque: 57,
          defensa: 69,
          resistencia: 69,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco Huerta",
        id: "bEBVrERPBvvIR08QHdM4A",
        habilidades: {
          ataque: 70,
          defensa: 60,
          resistencia: 60,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Rosendo Donoso-Santana",
        id: "A3LbZZVD0cAuBoFaI1Ysc",
        habilidades: {
          ataque: 67,
          defensa: 51,
          resistencia: 58,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Huerta",
        id: "LQp3CCG7FU2sXWsvtlBtk",
        habilidades: {
          ataque: 69,
          defensa: 61,
          resistencia: 63,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Solsona",
        id: "mJwu6Z8cLNPhBnRmg8zQ2",
        habilidades: {
          ataque: 63,
          defensa: 68,
          resistencia: 57,
        },
        posicion: "mediocampista",
        club: "Paraguay FC",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian de Gomila",
        id: "9AjByrSXddriouSGDpPao",
        habilidades: {
          ataque: 67,
          defensa: 60,
          resistencia: 51,
        },
        posicion: "mediocampista",
        club: "Paraguay FC",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Darren Luis de Páez",
        id: "nHCBozrqWuto5sIqCumqK",
        habilidades: {
          ataque: 54,
          defensa: 57,
          resistencia: 68,
        },
        posicion: "mediocampista",
        club: "Paraguay FC",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Marshall",
        id: "hZyiPnEDoUkDvvmQSsuxS",
        habilidades: {
          ataque: 68,
          defensa: 55,
          resistencia: 62,
        },
        posicion: "mediocampista",
        club: "Paraguay FC",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Hale",
        id: "MYfajwi7MxS8m69wBgebC",
        habilidades: {
          ataque: 65,
          defensa: 63,
          resistencia: 60,
        },
        posicion: "delantero",
        club: "Paraguay FC",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Huerta",
        id: "8dNPazrB0ek7ty3oP1zfm",
        habilidades: {
          ataque: 62,
          defensa: 56,
          resistencia: 65,
        },
        posicion: "delantero",
        club: "Paraguay FC",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Salvador Herrero",
        id: "jaxcaoVt4VzErwj3M3zKT",
        habilidades: {
          ataque: 66,
          defensa: 52,
          resistencia: 70,
        },
        posicion: "arquero",
        club: "Paraguay FC",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Tucker",
        id: "EC5-hrn9MwF1qfVFi9f7j",
        habilidades: {
          ataque: 63,
          defensa: 67,
          resistencia: 53,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Smith",
        id: "zzEtdeZ53UfpxY5Sz9tYP",
        habilidades: {
          ataque: 61,
          defensa: 60,
          resistencia: 52,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Albano Luis de Páez",
        id: "kZZUC_TlJAjI29hctta7t",
        habilidades: {
          ataque: 64,
          defensa: 67,
          resistencia: 69,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo Santos Morillo",
        id: "R39cduzpDytl5vt5rzrhX",
        habilidades: {
          ataque: 56,
          defensa: 64,
          resistencia: 65,
        },
        posicion: "defensa",
        club: "Paraguay FC",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};

const uruguayPlay = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Uruguay Play",
  id: "asmcIm6RF4-cpFSCIGqtV",
  nacionalidad: "Uruguay",
  logo: "logo5.jpg",
  keyPublica: "GBBOBHLHUUNBQR2M3VSE5PEOJZHGMPUS6CTXYB4Y2D35OW5VPUWHQQG2",
  keyPrivada: "SAZ5V7WC3BRENCDKUBZYN53LLLAQHNT2TF4N7EXL4S6GJKQE5CKC6SQF",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Bryant",
        id: "ZKaz_6DOercidSkSjS8WT",
        habilidades: {
          ataque: 67,
          defensa: 55,
          resistencia: 70,
        },
        posicion: "arquero",
        club: "Uruguay Play",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Jose Santos Morillo",
        id: "SlJDC2maYkazR6_ZCoORC",
        habilidades: {
          ataque: 60,
          defensa: 64,
          resistencia: 51,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adalberto Donoso-Santana",
        id: "05IEyHMLthkuKaf3-a-_2",
        habilidades: {
          ataque: 61,
          defensa: 60,
          resistencia: 52,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo Donoso-Santana",
        id: "KpytazfeUACzH_pp1QTFU",
        habilidades: {
          ataque: 68,
          defensa: 56,
          resistencia: 55,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Edwards",
        id: "U_QPnnQtbJrN7ZmisKLP6",
        habilidades: {
          ataque: 57,
          defensa: 63,
          resistencia: 59,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Jose Cañas",
        id: "ANkxv62TfnA5-wj3JgS6g",
        habilidades: {
          ataque: 52,
          defensa: 65,
          resistencia: 66,
        },
        posicion: "mediocampista",
        club: "Uruguay Play",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ricardo Mayoral Castillo",
        id: "2wmPWkWCDWPZ_897KY3kj",
        habilidades: {
          ataque: 59,
          defensa: 64,
          resistencia: 67,
        },
        posicion: "mediocampista",
        club: "Uruguay Play",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ricardo Smith",
        id: "So6D9_WGY9B8RY7TavREg",
        habilidades: {
          ataque: 63,
          defensa: 70,
          resistencia: 65,
        },
        posicion: "mediocampista",
        club: "Uruguay Play",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Edwards",
        id: "fXvEcWSCqIDemrL1EmJ3q",
        habilidades: {
          ataque: 63,
          defensa: 68,
          resistencia: 70,
        },
        posicion: "mediocampista",
        club: "Uruguay Play",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Huerta",
        id: "Kk7PWQ3tohdGy3cfMJd8Q",
        habilidades: {
          ataque: 70,
          defensa: 61,
          resistencia: 65,
        },
        posicion: "delantero",
        club: "Uruguay Play",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adalberto Donoso-Santana",
        id: "tkbRv3NRLNApL_otCvnuV",
        habilidades: {
          ataque: 57,
          defensa: 59,
          resistencia: 69,
        },
        posicion: "delantero",
        club: "Uruguay Play",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Palla Rozas",
        id: "CzOWtrG-3bPicFSUiCEBb",
        habilidades: {
          ataque: 61,
          defensa: 65,
          resistencia: 58,
        },
        posicion: "arquero",
        club: "Uruguay Play",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Felix Fischer",
        id: "HqLnknldHp4-ZyIkDfvLb",
        habilidades: {
          ataque: 61,
          defensa: 54,
          resistencia: 55,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Gil Santos Morillo",
        id: "43ppoZImMkRnnKdQmpah2",
        habilidades: {
          ataque: 59,
          defensa: 58,
          resistencia: 60,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco Fischer",
        id: "cpUiGF7fRPDUErpTatGWU",
        habilidades: {
          ataque: 68,
          defensa: 51,
          resistencia: 61,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Jose Walsh",
        id: "Ody2rLJFxiJbnAZEpwdQ8",
        habilidades: {
          ataque: 58,
          defensa: 59,
          resistencia: 65,
        },
        posicion: "defensa",
        club: "Uruguay Play",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};

const chilePatriots = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Chile Patriots",
  id: "RZW-6D4C9d43PEehHJOoR",
  nacionalidad: "Chile",
  logo: "logo4.jpg",
  keyPublica: "GDLNJUN4ASRDCRACIWEOXWFIAZ5PDROCKSWJSABWC65JJBNCXUV3OJUD",
  keyPrivada: "SCHFJXKXBWXLJSPNS4R27VR7B5OGSMFVIWH65OWPHBHQLXEGW3EJKGE3",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Jose Solsona",
        id: "PQsVvWO8Mr671b8gZd6yo",
        habilidades: {
          ataque: 64,
          defensa: 54,
          resistencia: 69,
        },
        posicion: "arquero",
        club: "Chile Patriots",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Eleuterio de Gomila",
        id: "z81m9w9E91-xV_TAO7-LT",
        habilidades: {
          ataque: 55,
          defensa: 53,
          resistencia: 59,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Nicanor Fischer",
        id: "9Kk8-CfRqXpdGFoJeERwE",
        habilidades: {
          ataque: 59,
          defensa: 64,
          resistencia: 69,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Felix Perez Sabater",
        id: "klBPwkMW_6qOYs-K2C40d",
        habilidades: {
          ataque: 65,
          defensa: 56,
          resistencia: 69,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Nicanor Brock",
        id: "Z6Pg1QWvPribobIhNqS18",
        habilidades: {
          ataque: 67,
          defensa: 70,
          resistencia: 60,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Luis de Páez",
        id: "V-TnPJC2Ige15lLwFg_45",
        habilidades: {
          ataque: 62,
          defensa: 62,
          resistencia: 56,
        },
        posicion: "mediocampista",
        club: "Chile Patriots",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo Tucker",
        id: "5vIF9KX7S0q0wn7vm72Kg",
        habilidades: {
          ataque: 68,
          defensa: 53,
          resistencia: 68,
        },
        posicion: "mediocampista",
        club: "Chile Patriots",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Jose Fischer",
        id: "mxiGObTLs3JWqjNgagx5B",
        habilidades: {
          ataque: 56,
          defensa: 68,
          resistencia: 57,
        },
        posicion: "mediocampista",
        club: "Chile Patriots",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Donoso-Santana",
        id: "NkNenozxhieo9ayJYkN2p",
        habilidades: {
          ataque: 54,
          defensa: 56,
          resistencia: 62,
        },
        posicion: "mediocampista",
        club: "Chile Patriots",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Fitzgerald",
        id: "rpS8ezjNswOjxrJIzWTlY",
        habilidades: {
          ataque: 68,
          defensa: 60,
          resistencia: 55,
        },
        posicion: "delantero",
        club: "Chile Patriots",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Albano Quesada Bernat",
        id: "Ps3l4k-WFwwLpS1KDk99v",
        habilidades: {
          ataque: 67,
          defensa: 65,
          resistencia: 58,
        },
        posicion: "delantero",
        club: "Chile Patriots",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ricardo Tucker",
        id: "o1xA29HAUlXSnr_V5huBK",
        habilidades: {
          ataque: 60,
          defensa: 52,
          resistencia: 69,
        },
        posicion: "arquero",
        club: "Chile Patriots",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Santos Morillo",
        id: "iXKIAHoNML9ouYutpZqSk",
        habilidades: {
          ataque: 58,
          defensa: 64,
          resistencia: 64,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Darren Salvador Herrero",
        id: "BUxit6XUYdCEBuIkiAt6g",
        habilidades: {
          ataque: 55,
          defensa: 67,
          resistencia: 57,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Victoriano Revilla Mena",
        id: "_OQGK1EWwL7PXBAeswhQc",
        habilidades: {
          ataque: 67,
          defensa: 68,
          resistencia: 53,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Santos Morillo",
        id: "tQ-60AfYYk3WWE3yWV-N8",
        habilidades: {
          ataque: 62,
          defensa: 66,
          resistencia: 58,
        },
        posicion: "defensa",
        club: "Chile Patriots",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};

const atleticoPeru = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Atletico Perú",
  id: "0-9pSR2B77SYHLtgDtvbU",
  nacionalidad: "Perú",
  logo: "logo3.jpg",
  keyPublica: "GDITLX33QXK4HKSEYZBAO6M3GZ5RPQNGLS2ASONGZV6CMGEHX4KUA4XK",
  keyPrivada: "SD4RXCSCOIS6V7DXCPSICSYOPTC3HEZESMDERLOOBWBZBSNX2SSTDHZV",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Fitzgerald",
        id: "6JetSLg3-7648NNJJcTI8",
        habilidades: {
          ataque: 63,
          defensa: 53,
          resistencia: 68,
        },
        posicion: "arquero",
        club: "Atletico Perú",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Smith",
        id: "CJB0GM2jLc2ZXwAMYezCI",
        habilidades: {
          ataque: 56,
          defensa: 62,
          resistencia: 52,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Walsh",
        id: "qrU0bbKPGhKkAe17vndvL",
        habilidades: {
          ataque: 64,
          defensa: 53,
          resistencia: 63,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Darren Donoso-Santana",
        id: "qu95zSQJrv4x-T_CW57ED",
        habilidades: {
          ataque: 51,
          defensa: 67,
          resistencia: 62,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Tucker",
        id: "lof0iMRtskwxBiIE4rrQF",
        habilidades: {
          ataque: 51,
          defensa: 62,
          resistencia: 63,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Fischer",
        id: "WIAz19JOWuAGMrS3LMQZt",
        habilidades: {
          ataque: 62,
          defensa: 61,
          resistencia: 60,
        },
        posicion: "mediocampista",
        club: "Atletico Perú",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Albano Palla Rozas",
        id: "Q9V049RJgH_jlVxoTrhdp",
        habilidades: {
          ataque: 52,
          defensa: 59,
          resistencia: 64,
        },
        posicion: "mediocampista",
        club: "Atletico Perú",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Felix Tucker",
        id: "w7-z5J091GsSUkTFjLg5Z",
        habilidades: {
          ataque: 60,
          defensa: 51,
          resistencia: 52,
        },
        posicion: "mediocampista",
        club: "Atletico Perú",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo Santos Morillo",
        id: "pqzUqF16A9_Et2iNHzDE4",
        habilidades: {
          ataque: 66,
          defensa: 69,
          resistencia: 54,
        },
        posicion: "mediocampista",
        club: "Atletico Perú",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Rosendo Palla Rozas",
        id: "dLvznilY558fLBP7eWPBE",
        habilidades: {
          ataque: 60,
          defensa: 52,
          resistencia: 56,
        },
        posicion: "delantero",
        club: "Atletico Perú",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Fischer",
        id: "0FtDSw0CvFYnOTxMHBK5V",
        habilidades: {
          ataque: 61,
          defensa: 64,
          resistencia: 62,
        },
        posicion: "delantero",
        club: "Atletico Perú",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo Fitzgerald",
        id: "o10tVXdsz2feH0aOYUGBM",
        habilidades: {
          ataque: 53,
          defensa: 62,
          resistencia: 68,
        },
        posicion: "arquero",
        club: "Atletico Perú",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Luis de Páez",
        id: "8oFW_JRR16ArZQe0Il_l3",
        habilidades: {
          ataque: 56,
          defensa: 57,
          resistencia: 64,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Serra-Gras",
        id: "l2pFNBuFNZuQEHIZ1fE_r",
        habilidades: {
          ataque: 58,
          defensa: 53,
          resistencia: 53,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Eleuterio Victoriano Revilla Mena",
        id: "AWZ3HPn1hnBqM-udyE6df",
        habilidades: {
          ataque: 69,
          defensa: 67,
          resistencia: 70,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Jose Perez Sabater",
        id: "F14nYPn57HssbT6EZGZ2l",
        habilidades: {
          ataque: 69,
          defensa: 63,
          resistencia: 70,
        },
        posicion: "defensa",
        club: "Atletico Perú",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};

const boliviaUnited = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Bolivia United",
  id: "9ZGpYbsT5qAX-M03SDI6I",
  nacionalidad: "Bolivia",
  logo: "logo2.jpg",
  keyPublica: "GDGJCGOVGY4TQ5KEVKRB3FVWO3SNCNWJLHYAS7LCLPN7WVV5HMGK3YRD",
  keyPrivada: "SD2LF7LB5ANLGYZGKQ3OH2W5VO6NNFK5MMXQSZ7A3325SEZOIANJVAXN",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Cañas",
        id: "SuQU5iEuoEKT9m2MS1CbY",
        habilidades: {
          ataque: 64,
          defensa: 54,
          resistencia: 69,
        },
        posicion: "arquero",
        club: "Bolivia United",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Hale",
        id: "dWGKWzaZGS5fkGNfbAvuJ",
        habilidades: {
          ataque: 57,
          defensa: 66,
          resistencia: 61,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Gil Edwards",
        id: "P46ZYDWxOslaF5-WBqyiT",
        habilidades: {
          ataque: 54,
          defensa: 58,
          resistencia: 64,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Rosendo Walsh",
        id: "QgvmBVswDMQWuE1jm_-Ey",
        habilidades: {
          ataque: 51,
          defensa: 61,
          resistencia: 69,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Tucker",
        id: "n155Q-RmwlpxH2bY3fDGo",
        habilidades: {
          ataque: 63,
          defensa: 68,
          resistencia: 57,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Santos Morillo",
        id: "I18UZD5ATroZh4IXCrZno",
        habilidades: {
          ataque: 65,
          defensa: 69,
          resistencia: 59,
        },
        posicion: "mediocampista",
        club: "Bolivia United",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Donoso-Santana",
        id: "NX_LPD6aSS-xvn-pQdyel",
        habilidades: {
          ataque: 53,
          defensa: 62,
          resistencia: 52,
        },
        posicion: "mediocampista",
        club: "Bolivia United",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco del Ayllón",
        id: "nlyvs_Xn2l_ZG2t3ICXaj",
        habilidades: {
          ataque: 54,
          defensa: 67,
          resistencia: 52,
        },
        posicion: "mediocampista",
        club: "Bolivia United",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Quesada Bernat",
        id: "r-1TMdeF9SbKycZBXzQvO",
        habilidades: {
          ataque: 69,
          defensa: 62,
          resistencia: 65,
        },
        posicion: "mediocampista",
        club: "Bolivia United",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Luis de Páez",
        id: "GtisBQN7P47I4SZafQSxI",
        habilidades: {
          ataque: 60,
          defensa: 69,
          resistencia: 59,
        },
        posicion: "delantero",
        club: "Bolivia United",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Quesada Bernat",
        id: "aPKzSdGV3xDMlmf5VGCb8",
        habilidades: {
          ataque: 63,
          defensa: 67,
          resistencia: 69,
        },
        posicion: "delantero",
        club: "Bolivia United",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Palla Rozas",
        id: "S9CLCfHuEJFY9qLL9367G",
        habilidades: {
          ataque: 60,
          defensa: 57,
          resistencia: 54,
        },
        posicion: "arquero",
        club: "Bolivia United",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Mayoral Castillo",
        id: "R9E1r9jNMwxob3cMLm8tx",
        habilidades: {
          ataque: 67,
          defensa: 65,
          resistencia: 63,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Albano Donoso-Santana",
        id: "0GOyzr052_7HVavTlq2bq",
        habilidades: {
          ataque: 62,
          defensa: 62,
          resistencia: 69,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Curtis Donoso-Santana",
        id: "W8PczjDdHy72LLwnnkK-M",
        habilidades: {
          ataque: 60,
          defensa: 51,
          resistencia: 51,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Mayoral Castillo",
        id: "1obbAwEIklr5Idk5jbAXd",
        habilidades: {
          ataque: 55,
          defensa: 52,
          resistencia: 70,
        },
        posicion: "defensa",
        club: "Bolivia United",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};

const ecuadorFutbolClub = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Ecuador Futbol Club",
  id: "X5mVP8VMpPrDap0RhRNP2",
  nacionalidad: "Ecuador",
  logo: "logo1.jpg",
  keyPublica: "GBTIMJWBFA3IGEI3CLLIZ6W3FWV5H7DSATTILZXDEQCEDOC6EVQJWAEA",
  keyPrivada: "SDNKZC6D6GQTPKLVJP6IQN3FCFHZSYA3JNXL5BPDQN2RBNVEDHIO324G",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Smith",
        id: "rUDc8jtZQACftm-7xGEW2",
        habilidades: {
          ataque: 60,
          defensa: 58,
          resistencia: 60,
        },
        posicion: "arquero",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ricardo Donoso-Santana",
        id: "5v0p8Ki-OLyyEeerXb3PA",
        habilidades: {
          ataque: 65,
          defensa: 64,
          resistencia: 63,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark del Ayllón",
        id: "NI-jHgFrWcVEiEXXyAJYU",
        habilidades: {
          ataque: 68,
          defensa: 60,
          resistencia: 62,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Albano Fitzgerald",
        id: "VBC_6np_EW5VV_b3NZYcG",
        habilidades: {
          ataque: 52,
          defensa: 69,
          resistencia: 52,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Jose Victoriano Revilla Mena",
        id: "wlIUJPMj_Wh63h8S5s668",
        habilidades: {
          ataque: 61,
          defensa: 51,
          resistencia: 63,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Nicanor Baró-Carreño",
        id: "fm8TBlevf1yh26A5QCAtC",
        habilidades: {
          ataque: 60,
          defensa: 61,
          resistencia: 60,
        },
        posicion: "mediocampista",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Curtis Carson",
        id: "163qtUDuXHWdiq51UnuOl",
        habilidades: {
          ataque: 63,
          defensa: 69,
          resistencia: 61,
        },
        posicion: "mediocampista",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Curtis Edwards",
        id: "-BBcoQ5rwe9ZTiscYmFlf",
        habilidades: {
          ataque: 67,
          defensa: 51,
          resistencia: 67,
        },
        posicion: "mediocampista",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Perez Sabater",
        id: "-LuxA0NWvOh5wsL1odTQM",
        habilidades: {
          ataque: 69,
          defensa: 56,
          resistencia: 68,
        },
        posicion: "mediocampista",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Tucker",
        id: "3fBvzWUJbuanelK3gEfJd",
        habilidades: {
          ataque: 61,
          defensa: 52,
          resistencia: 51,
        },
        posicion: "delantero",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Brock",
        id: "GaCy-bzF2_GAiNE-GFbnY",
        habilidades: {
          ataque: 64,
          defensa: 70,
          resistencia: 53,
        },
        posicion: "delantero",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo del Ayllón",
        id: "yZi-EEXR2P3v9ZRnS9Zl5",
        habilidades: {
          ataque: 68,
          defensa: 70,
          resistencia: 70,
        },
        posicion: "arquero",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Smith",
        id: "cAiLHFUdHgoQ_DSa_3RDI",
        habilidades: {
          ataque: 56,
          defensa: 60,
          resistencia: 54,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Felix Luis de Páez",
        id: "cMnUVwFdlccuJn4P7U4JO",
        habilidades: {
          ataque: 63,
          defensa: 70,
          resistencia: 67,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Brock",
        id: "jm_sOz9uPLRn17fwrQE1F",
        habilidades: {
          ataque: 55,
          defensa: 51,
          resistencia: 59,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco Bryant",
        id: "gpxznCuJfMYNKAL8wNSzG",
        habilidades: {
          ataque: 54,
          defensa: 68,
          resistencia: 57,
        },
        posicion: "defensa",
        club: "Ecuador Futbol Club",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};
const clubNacionalGuyana = {
  puntosTorneo: 0,
  partidosJugados: 0,
  partidosGanados: 0,
  partidosPerdidos: 0,
  partidosEmpatados: 0,
  golesPositivos: 0,
  golesNegativos: 0,
  posicionTorneo: "",
  anioCreacion: "2022",
  fixture: {},
  nombre: "Club Nacional Guyana",
  id: "4rRnzkw2uolMRWD4SnIME",
  nacionalidad: "Guyana",
  logo: "logo0.jpg",
  keyPublica: "GAUMKWKZ2JMH546EEAIWLODZC6ZED5FVP4VUFRHMVG7XP6QNNZU34Q3B",
  keyPrivada: "SCE5UXZQ6ONVXNAEK6WFXRYL44VZQ5UH557WPG227IDZJ6EK5AM55CZC",
  jugadores: {
    titulares: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adrián Victoriano Revilla Mena",
        id: "hOfcpq2C0Nv5-pMHfFOpJ",
        habilidades: {
          ataque: 66,
          defensa: 67,
          resistencia: 56,
        },
        posicion: "arquero",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars0.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Isaías Smith",
        id: "8rJhN-evpMS41m1gRtHZt",
        habilidades: {
          ataque: 60,
          defensa: 58,
          resistencia: 51,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars1.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Segismundo Smith",
        id: "ZNoN8T0LPn_EN_wpuQV1R",
        habilidades: {
          ataque: 69,
          defensa: 54,
          resistencia: 59,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars2.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Curtis Brock",
        id: "W4lsBk5exvBkosndtf23D",
        habilidades: {
          ataque: 54,
          defensa: 59,
          resistencia: 51,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars3.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Rosendo Bryant",
        id: "T5BoneXJFUOHiLzr9buuk",
        habilidades: {
          ataque: 62,
          defensa: 53,
          resistencia: 53,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars4.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Ian Tucker",
        id: "8ViI6ToowQJeOB2qnAKE5",
        habilidades: {
          ataque: 64,
          defensa: 61,
          resistencia: 59,
        },
        posicion: "mediocampista",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars5.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Huerta",
        id: "3urn36EKjnsn7a_an5Fnt",
        habilidades: {
          ataque: 70,
          defensa: 63,
          resistencia: 65,
        },
        posicion: "mediocampista",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars6.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Adalberto Smith",
        id: "mOfiksu4I1KbujLGIDcsf",
        habilidades: {
          ataque: 60,
          defensa: 58,
          resistencia: 54,
        },
        posicion: "mediocampista",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars7.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Joel Hale",
        id: "wIYIwwpH1bxR4oZ9WDm7P",
        habilidades: {
          ataque: 66,
          defensa: 53,
          resistencia: 67,
        },
        posicion: "mediocampista",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars8.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Horacio Santos Morillo",
        id: "wwwROY8xxBcurm6p2SMD_",
        habilidades: {
          ataque: 65,
          defensa: 63,
          resistencia: 55,
        },
        posicion: "delantero",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars9.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Perez Sabater",
        id: "0Zxl_DNQeVTMogS1rIGGY",
        habilidades: {
          ataque: 51,
          defensa: 51,
          resistencia: 65,
        },
        posicion: "delantero",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars10.png",
      },
    ],
    suplentes: [
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Bartolomé Serra-Gras",
        id: "BiJy3eAvPVlwypHbfpoyx",
        habilidades: {
          ataque: 59,
          defensa: 67,
          resistencia: 65,
        },
        posicion: "arquero",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars11.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Gil Perez Sabater",
        id: "kRdpBTOhmoK_EVksIKgf7",
        habilidades: {
          ataque: 52,
          defensa: 68,
          resistencia: 64,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars12.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Vasco Huerta",
        id: "QpFxn77wLXdTqiFNrCBvB",
        habilidades: {
          ataque: 63,
          defensa: 52,
          resistencia: 52,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars13.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Albano Cañas",
        id: "PNPRThca14-JHh2LS38r5",
        habilidades: {
          ataque: 60,
          defensa: 66,
          resistencia: 62,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars14.png",
      },
      {
        puedeJugar: true,
        jugadorEnVenta: false,
        nombre: "Mark Quesada Bernat",
        id: "_YsWrxaE_p-mdgI-1jl8f",
        habilidades: {
          ataque: 59,
          defensa: 51,
          resistencia: 54,
        },
        posicion: "defensa",
        club: "Club Nacional Guyana",
        imagenPerfil: "avataaars15.png",
      },
    ],
    deshabilitados: [],
  },
};
