const datosTorneo = [
  {
    posicion: 1,
    nombre: "ARGENTINA FC",
    puntosTorneo: 24,
    partidosJugados: 8,
    partidosGanados: 8,
    partidosPerdidos: 0,
    partidosEmpatados: 0,
    golesPositivos: 10,
    golesNegativos: 0,
  },
  {
    posicion: 2,
    nombre: "BRASIL SPORTS",
    puntosTorneo: 20,
    partidosJugados: 8,
    partidosGanados: 6,
    partidosPerdidos: 0,
    partidosEmpatados: 2,
    golesPositivos: 11,
    golesNegativos: 4,
  },
  {
    posicion: 3,
    nombre: "COLOMBIA BULLS",
    puntosTorneo: 16,
    partidosJugados: 8,
    partidosGanados: 5,
    partidosPerdidos: 0,
    partidosEmpatados: 1,
    golesPositivos: 14,
    golesNegativos: 7,
  },
  {
    posicion: 4,
    nombre: "PARAGUAY FC",
    puntosTorneo: 15,
    partidosJugados: 8,
    partidosGanados: 4,
    partidosPerdidos: 1,
    partidosEmpatados: 3,
    golesPositivos: 10,
    golesNegativos: 12,
  },
  {
    posicion: 5,
    nombre: "URUGUAY PLAY",
    puntosTorneo: 12,
    partidosJugados: 8,
    partidosGanados: 4,
    partidosPerdidos: 4,
    partidosEmpatados: 0,
    golesPositivos: 6,
    golesNegativos: 11,
  },
  {
    posicion: 6,
    nombre: "CHILE PATRIOTS",
    puntosTorneo: 11,
    partidosJugados: 8,
    partidosGanados: 8,
    partidosPerdidos: 0,
    partidosEmpatados: 0,
    golesPositivos: 8,
    golesNegativos: 5,
  },
  {
    posicion: 7,
    nombre: "ATLETICO PERU",
    puntosTorneo: 10,
    partidosJugados: 8,
    partidosGanados: 2,
    partidosPerdidos: 2,
    partidosEmpatados: 4,
    golesPositivos: 10,
    golesNegativos: 10,
  },
  {
    posicion: 8,
    nombre: "BOLIVIA UNITED",
    puntosTorneo: 8,
    partidosJugados: 8,
    partidosGanados: 1,
    partidosPerdidos: 1,
    partidosEmpatados: 6,
    golesPositivos: 5,
    golesNegativos: 12,
  },
  {
    posicion: 9,
    nombre: "ECUADOR FUTBOL CLUB",
    puntosTorneo: 7,
    partidosJugados: 8,
    partidosGanados: 0,
    partidosPerdidos: 0,
    partidosEmpatados: 7,
    golesPositivos: 10,
    golesNegativos: 15,
  },
  {
    posicion: 10,
    nombre: "CLUB NACIONAL GUAYANA",
    puntosTorneo: 1,
    partidosJugados: 8,
    partidosGanados: 0,
    partidosPerdidos: 0,
    partidosEmpatados: 1,
    golesPositivos: 1,
    golesNegativos: 20,
  },
];
export default datosTorneo